export { default as Article } from './article/Article';
export { default as Brand } from './brand/Brand';
// export { default as CTA } from './cta/CTA';
export { default as Avantage } from './avantage/Avantage';
export { default as Navbar } from './navbar/Navbar';
export { default as Login } from './login/Login';
export { default as Formulaire } from './formulaire/Formulaire';
export { default as Formulaire2 } from './formulaire2/Formulaire2';
export { default as UserInterface } from './userInterface/UserInterface';
// export { default as LigneRecu } from './recu/LigneRecu';
export { default as Renseignement } from './renseignement/Renseignement';
export { default as Historique } from './historique/Historique';
